'use client';

import { useState, useCallback } from 'react';
import type { ScanResult, FundedDependency } from '@/types';
import { FundingBadge } from './FundingBadge';
import { StatsBar } from './StatsBar';

interface ScanReportProps {
  result: ScanResult;
  onReset: () => void;
}

type Filter = 'all' | 'funded' | 'unfunded';
type SortKey = 'name' | 'funded';

export function ScanReport({ result, onReset }: ScanReportProps) {
  const [filter, setFilter] = useState<Filter>('all');
  const [sort, setSort] = useState<SortKey>('funded');
  const [search, setSearch] = useState('');
  const [copied, setCopied] = useState(false);

  const filtered = result.dependencies
    .filter((d) => {
      if (filter === 'funded') return d.hasFunding;
      if (filter === 'unfunded') return !d.hasFunding;
      return true;
    })
    .filter((d) =>
      d.name.toLowerCase().includes(search.toLowerCase())
    )
    .sort((a, b) => {
      if (sort === 'funded') {
        if (a.hasFunding === b.hasFunding) return a.name.localeCompare(b.name);
        return a.hasFunding ? -1 : 1;
      }
      return a.name.localeCompare(b.name);
    });

  const handleExportJson = useCallback(() => {
    const blob = new Blob([JSON.stringify(result, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'depfund-report.json';
    a.click();
    URL.revokeObjectURL(url);
  }, [result]);

  const handleExportMarkdown = useCallback(() => {
    const pct = Math.round(
      (result.fundedCount / result.totalDependencies) * 100
    );
    const rows = result.dependencies
      .map((d) => {
        const links = d.funding.map((f) => `[${f.type}](${f.url})`).join(', ');
        return `| ${d.name} | ${d.version} | ${d.hasFunding ? '✅' : '❌'} | ${links || '—'} |`;
      })
      .join('\n');

    const md = [
      `# depfund report — ${result.projectName}`,
      '',
      `> Generated by [depfund](https://github.com/darcszn/depfund) on ${result.scannedAt}`,
      '',
      `## Summary`,
      '',
      `| Metric | Value |`,
      `| --- | --- |`,
      `| Ecosystem | ${result.ecosystem} |`,
      `| Total dependencies | ${result.totalDependencies} |`,
      `| With funding info | ${result.fundedCount} (${pct}%) |`,
      `| Without funding info | ${result.unfundedCount} |`,
      '',
      `## Dependencies`,
      '',
      `| Package | Version | Has Funding | Funding Links |`,
      `| --- | --- | --- | --- |`,
      rows,
      '',
      '---',
      '*Generated by [depfund](https://github.com/darcszn/depfund)*',
    ].join('\n');

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'depfund-report.md';
    a.click();
    URL.revokeObjectURL(url);
  }, [result]);

  const handleCopyJson = useCallback(async () => {
    await navigator.clipboard.writeText(JSON.stringify(result, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [result]);

  return (
    <div className="space-y-6">
      {/* Top bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div>
          <h2 className="text-xl font-bold text-slate-900">
            {result.projectName}
            <span className="ml-2 text-sm font-normal text-slate-400">
              ({result.ecosystem})
            </span>
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Scanned {result.totalDependencies} dependencies ·{' '}
            {new Date(result.scannedAt).toLocaleString()}
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleCopyJson}
            className="text-xs px-3 py-1.5 rounded-lg border border-slate-200 text-slate-600
                       hover:border-slate-300 hover:bg-slate-50 transition-all"
          >
            {copied ? '✓ Copied!' : 'Copy JSON'}
          </button>
          <button
            onClick={handleExportJson}
            className="text-xs px-3 py-1.5 rounded-lg border border-slate-200 text-slate-600
                       hover:border-slate-300 hover:bg-slate-50 transition-all"
          >
            Export JSON
          </button>
          <button
            onClick={handleExportMarkdown}
            className="text-xs px-3 py-1.5 rounded-lg border border-slate-200 text-slate-600
                       hover:border-slate-300 hover:bg-slate-50 transition-all"
          >
            Export MD
          </button>
          <button
            onClick={onReset}
            className="text-xs px-3 py-1.5 rounded-lg bg-slate-900 text-white
                       hover:bg-slate-700 transition-all"
          >
            ← New scan
          </button>
        </div>
      </div>

      {/* Stats */}
      <StatsBar result={result} />

      {/* Filters & search */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="flex rounded-lg border border-slate-200 overflow-hidden text-sm">
          {(['all', 'funded', 'unfunded'] as Filter[]).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-4 py-2 capitalize transition-colors ${
                filter === f
                  ? 'bg-green-600 text-white'
                  : 'bg-white text-slate-600 hover:bg-slate-50'
              }`}
            >
              {f}
              {f === 'funded' && (
                <span className="ml-1.5 text-xs opacity-75">
                  ({result.fundedCount})
                </span>
              )}
              {f === 'unfunded' && (
                <span className="ml-1.5 text-xs opacity-75">
                  ({result.unfundedCount})
                </span>
              )}
            </button>
          ))}
        </div>

        <input
          type="text"
          placeholder="Search packages…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="flex-1 px-4 py-2 border border-slate-200 rounded-lg text-sm
                     focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent"
          aria-label="Search packages"
        />

        <select
          value={sort}
          onChange={(e) => setSort(e.target.value as SortKey)}
          className="px-3 py-2 border border-slate-200 rounded-lg text-sm text-slate-600
                     focus:outline-none focus:ring-2 focus:ring-green-500 bg-white"
          aria-label="Sort by"
        >
          <option value="funded">Sort: Funded first</option>
          <option value="name">Sort: Name A–Z</option>
        </select>
      </div>

      {/* Dependency list */}
      <div className="space-y-2">
        {filtered.length === 0 ? (
          <div className="text-center py-12 text-slate-400">
            No packages match your filters.
          </div>
        ) : (
          filtered.map((dep) => (
            <DependencyRow key={`${dep.ecosystem}:${dep.name}`} dep={dep} />
          ))
        )}
      </div>

      <p className="text-xs text-center text-slate-400">
        Showing {filtered.length} of {result.totalDependencies} packages ·
        Data from npm, PyPI, crates.io &amp; GitHub FUNDING.yml
      </p>
    </div>
  );
}

function DependencyRow({ dep }: { dep: FundedDependency }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div
      className={`rounded-lg border transition-all ${
        dep.hasFunding
          ? 'border-green-200 bg-green-50/30'
          : 'border-slate-200 bg-white'
      }`}
    >
      <div
        className="flex items-center gap-3 px-4 py-3 cursor-pointer select-none"
        onClick={() => setExpanded((p) => !p)}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === 'Enter' && setExpanded((p) => !p)}
        aria-expanded={expanded}
      >
        {/* Funding indicator */}
        <div
          className={`w-2 h-2 rounded-full flex-shrink-0 ${
            dep.hasFunding ? 'bg-green-500' : 'bg-slate-300'
          }`}
          aria-label={dep.hasFunding ? 'Has funding' : 'No funding'}
        />

        {/* Package name & version */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-mono text-sm font-medium text-slate-800 truncate">
              {dep.name}
            </span>
            <span className="text-xs text-slate-400 font-mono">{dep.version}</span>
            <span className={`text-xs px-1.5 py-0.5 rounded-full font-medium
              ${dep.ecosystem === 'npm' ? 'bg-red-50 text-red-600' :
                dep.ecosystem === 'pypi' ? 'bg-blue-50 text-blue-600' :
                'bg-orange-50 text-orange-600'}`}>
              {dep.ecosystem}
            </span>
          </div>
          {dep.description && (
            <p className="text-xs text-slate-400 mt-0.5 truncate">{dep.description}</p>
          )}
        </div>

        {/* Right side: funding badges */}
        <div className="flex items-center gap-2 flex-shrink-0">
          {dep.funding.slice(0, 3).map((f) => (
            <FundingBadge key={f.url} link={f} />
          ))}
          {dep.funding.length > 3 && (
            <span className="text-xs text-slate-400">+{dep.funding.length - 3}</span>
          )}
          {!dep.hasFunding && (
            <span className="text-xs text-slate-400">No funding</span>
          )}
          <svg
            className={`w-4 h-4 text-slate-400 transition-transform ${expanded ? 'rotate-180' : ''}`}
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </div>

      {/* Expanded details */}
      {expanded && (
        <div className="border-t border-slate-100 px-4 py-3 space-y-2">
          {dep.repositoryUrl && (
            <div className="flex items-center gap-2 text-xs">
              <span className="text-slate-400 w-20">Repository</span>
              <a
                href={dep.repositoryUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-green-600 hover:underline truncate"
                onClick={(e) => e.stopPropagation()}
              >
                {dep.repositoryUrl}
              </a>
            </div>
          )}

          {dep.funding.length > 0 ? (
            <div className="space-y-1">
              <span className="text-xs text-slate-400">Funding links</span>
              <div className="flex flex-wrap gap-2 mt-1">
                {dep.funding.map((f) => (
                  <a
                    key={f.url}
                    href={f.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    className="flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-full
                               bg-white border border-green-200 text-green-700 hover:bg-green-50 transition-colors"
                  >
                    <FundingTypeIcon type={f.type} />
                    {f.type}
                  </a>
                ))}
              </div>
            </div>
          ) : (
            <p className="text-xs text-slate-400">
              No funding links found for this package. Consider contributing or opening an issue.
            </p>
          )}
        </div>
      )}
    </div>
  );
}

function FundingTypeIcon({ type }: { type: string }) {
  const icons: Record<string, string> = {
    github: '🐙',
    patreon: '🎨',
    opencollective: '🌐',
    ko_fi: '☕',
    liberapay: '💛',
    tidelift: '🔒',
    custom: '🔗',
  };
  return <span aria-hidden="true">{icons[type] || '💰'}</span>;
}
