import type { ScanResult } from './types.js';

// ─── Terminal output ──────────────────────────────────────────────────────────

// Dynamic imports for ESM-only packages
let _chalk: typeof import('chalk').default | null = null;
async function getChalk() {
  if (!_chalk) {
    const m = await import('chalk');
    _chalk = m.default;
  }
  return _chalk;
}

let _Table: (typeof import('cli-table3'))['default'] | null = null;
async function getTable() {
  if (!_Table) {
    const m = await import('cli-table3');
    _Table = m.default;
  }
  return _Table;
}

export async function printTable(result: ScanResult): Promise<void> {
  const chalk = await getChalk();
  const Table = await getTable();

  console.log();
  console.log(
    chalk.bold.cyan('depfund') +
      chalk.dim(' — ') +
      chalk.bold(result.projectName) +
      chalk.dim(` (${result.ecosystem})`)
  );
  console.log(
    chalk.dim(
      `Scanned ${result.totalDependencies} dependencies on ${result.scannedAt}`
    )
  );
  console.log();

  const table = new Table({
    head: [
      chalk.bold('Package'),
      chalk.bold('Version'),
      chalk.bold('Funding'),
      chalk.bold('Links'),
    ],
    colWidths: [30, 12, 10, 50],
    wordWrap: true,
  });

  for (const dep of result.dependencies) {
    const fundingBadge = dep.hasFunding
      ? chalk.green('✔ yes')
      : chalk.red('✘ no');

    const links = dep.funding
      .slice(0, 2)
      .map((f) => chalk.dim(`[${f.type}] `) + chalk.cyan(f.url))
      .join('\n');

    table.push([dep.name, dep.version, fundingBadge, links || chalk.dim('—')]);
  }

  console.log(table.toString());
  console.log();

  const pct = result.totalDependencies > 0
    ? Math.round((result.fundedCount / result.totalDependencies) * 100)
    : 0;

  console.log(
    chalk.bold(`Summary: `) +
      chalk.green(`${result.fundedCount} funded`) +
      chalk.dim(' / ') +
      chalk.red(`${result.unfundedCount} unfunded`) +
      chalk.dim(` (${pct}% of your deps have funding info)`)
  );
  console.log();
}

// ─── JSON output ──────────────────────────────────────────────────────────────

export function toJson(result: ScanResult): string {
  return JSON.stringify(result, null, 2);
}

// ─── Markdown output ──────────────────────────────────────────────────────────

export function toMarkdown(result: ScanResult): string {
  const lines: string[] = [];
  const pct = result.totalDependencies > 0
    ? Math.round((result.fundedCount / result.totalDependencies) * 100)
    : 0;

  lines.push(`# depfund report — ${result.projectName}`);
  lines.push('');
  lines.push(
    `> Generated by [depfund](https://github.com/darcszn/depfund) on ${result.scannedAt}`
  );
  lines.push('');
  lines.push(`## Summary`);
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Ecosystem | ${result.ecosystem} |`);
  lines.push(`| Total dependencies | ${result.totalDependencies} |`);
  lines.push(`| With funding info | ${result.fundedCount} (${pct}%) |`);
  lines.push(`| Without funding info | ${result.unfundedCount} |`);
  lines.push('');
  lines.push(`## Dependencies`);
  lines.push('');
  lines.push(`| Package | Version | Has Funding | Funding Links |`);
  lines.push(`| --- | --- | --- | --- |`);

  for (const dep of result.dependencies) {
    const links = dep.funding.map((f) => `[${f.type}](${f.url})`).join(', ');
    lines.push(
      `| ${dep.name} | ${dep.version} | ${dep.hasFunding ? '✅' : '❌'} | ${
        links || '—'
      } |`
    );
  }

  lines.push('');
  lines.push('---');
  lines.push(
    '*Generated by [depfund](https://github.com/darcszn/depfund)*'
  );

  return lines.join('\n');
}
